services:
  indexer-base:
    container_name: mainnet-indexer-base
    build:
      context: .
      dockerfile: ./apps/indexer-base/Dockerfile
    restart: always
    networks:
      - my_custom_bridge
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: mainnet.indexer.env

networks:
  my_custom_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
        
volumes:
  redis-data:
