version: '3.6'
services:
  api:
    container_name: testnet-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.api.env
    ports:
      - 'http://206.238.197.207:3008'
volumes:
  redis-data:
